### ISSUE TITLE
Add extra with signature which auto picks props

### ISSUE THREAD

**Issue by sospedra** [sospedra/mayre#2]
An array where the first position are the props and the next the name of the ones to be picked up.

Just like this:

```js
<Mayre
  of={Something}
  with={[props, 'propA', 'propB']}
/>
```

**Comment by Schniz** [comment]
what does `[props, 'propA', 'propB']` mean in this context?

**Comment by sospedra** [comment]
It's a signature like the [lodash `pick` one](https://lodash.com/docs/4.17.4#pick)
Given an object `props`
Select those `attributes` mathching the `arguments` tailing strings

**Comment by sospedra** [comment]
@Schniz ready at v2.3.0 🚀
