### ISSUE TITLE
How is it compared to Recompose render methods

### ISSUE THREAD

**Issue by benxgao** [sospedra/mayre#8]
[renderComponent](https://github.com/acdlite/recompose/blob/master/docs/API.md#rendercomponent) and [renderNothing](https://github.com/acdlite/recompose/blob/master/docs/API.md#rendernothing)

**Comment by sospedra** [comment]
Hi @benxgao from my understanding of Recompose those methods are HOC. Meaning that the idea of working only from the JSX side is lost.

I'd say also that with Mayre you have a slightly more powerful syntax: there's either feature, props sharing, props picking, etc.

And, finally, speaking in terms of functionalities. Mayre is somewhat a combination of both Recompose methods. By using the mandatory prop `when` you're rendering a component `renderComponent` or nothing `renderNothing`.

Hope it helps ;)

**Comment by sospedra** [comment]
@benxgao Reopen if you feel like this doubt is not resolved ;)
