### ISSUE TITLE
UglifyJs Name expected

### ISSUE THREAD

**Issue by gtrias** [sospedra/mayre#9]
I cannot build project using mayre. It throws an error related with UglifyJs:

```
[genar@fry fees-widget]$ npm run build

> fees-widget@0.2.6 build /home/genar/src/components/fees-widget
> node scripts/build.js

Creating an optimized production build...
Skipping static resource "/home/genar/src/components/fees-widget/build/static/js/main.js" (2.16 MB) - max size is 2.1 MB
Failed to compile.

static/js/main.js from UglifyJs
Name expected [./~/mayre/dist/mayre.min.js:1,13][static/js/main.js:14007,5]
```
Any tip to make it working?

**Comment by sospedra** [comment]
Did you?

`git clone https://github.com/sospedra/mayre.git`
`cd mayre`
`yarn`
`npm run build`

I just tried from a clean and it worked. Ensure you're installing with `yarn` cause freezing versions may vary.

**Comment by sospedra** [comment]
Do you mean you have Mayre as a dep in your project and your build is not working?

Then, can you post your build script and configs?

**Comment by gtrias** [comment]
Hey @sospedra sorry to not provide more details before.

I've created a repo reproducing this error:

**Comment by sospedra** [comment]
I'll take a look this Saturday ;)

**Comment by gtrias** [comment]
Thanks @sospedra ! :)

**Comment by sospedra** [comment]
Fixed in new [v3.0.0](https://github.com/sospedra/mayre/releases/tag/v3.0.0) 🎉
At 0794db053248e647985c10d1dcdb0f594c4a9fbc

**Comment by gtrias** [comment]
Thank you so much @sospedra . Today I'll try in my projects :)

**Comment by gtrias** [comment]
I finally tried to build a project with mayre and I confirm the issue is fixed, thanks a lot!
